REM building ...

node gettext.js -s "../public/app/ibman/lang/ru.po ../system/access.control/lang/ru.po"
node gettext.js -s "../public/app/ibman/lang/de.po ../system/access.control/lang/de.po"
node gettext.js -s "../public/app/ibman/lang/bg.po ../system/access.control/lang/bg.po"
node gettext.js -s "../public/app/ibman/lang/uk.po ../system/access.control/lang/uk.po"
node gettext.js -s "../public/app/ibman/lang/tr.po ../system/access.control/lang/tr.po"
node gettext.js -s "../public/app/ibman/lang/el.po ../system/access.control/lang/el.po"

node gettext.js -s "../public/app/dlman/lang/ru.po ../system/access.control/lang/ru.po"
node gettext.js -s "../public/app/dlman/lang/de.po ../system/access.control/lang/de.po"
node gettext.js -s "../public/app/dlman/lang/bg.po ../system/access.control/lang/bg.po"
node gettext.js -s "../public/app/dlman/lang/uk.po ../system/access.control/lang/uk.po"
node gettext.js -s "../public/app/dlman/lang/es.po ../system/access.control/lang/es.po"
node gettext.js -s "../public/app/dlman/lang/tr.po ../system/access.control/lang/tr.po"
node gettext.js -s "../public/app/dlman/lang/el.po ../system/access.control/lang/el.po"

node gettext.js -s "../public/app/pvr/lang/ru.po"
node gettext.js -s "../public/app/pvr/lang/de.po"
node gettext.js -s "../public/app/pvr/lang/bg.po"
node gettext.js -s "../public/app/pvr/lang/uk.po"
node gettext.js -s "../public/app/pvr/lang/es.po"
node gettext.js -s "../public/app/pvr/lang/tr.po"
node gettext.js -s "../public/app/pvr/lang/el.po"

node gettext.js -s "../public/app/help/lang/ru.po"
node gettext.js -s "../public/app/help/lang/de.po"
node gettext.js -s "../public/app/help/lang/bg.po"
node gettext.js -s "../public/app/help/lang/uk.po"
node gettext.js -s "../public/app/help/lang/es.po"
node gettext.js -s "../public/app/help/lang/tr.po"
node gettext.js -s "../public/app/help/lang/el.po"

node gettext.js -s "../public/portal/master_settings/lang/ru.po"
node gettext.js -s "../public/portal/master_settings/lang/de.po"
node gettext.js -s "../public/portal/master_settings/lang/bg.po"
node gettext.js -s "../public/portal/master_settings/lang/uk.po"
node gettext.js -s "../public/portal/master_settings/lang/es.po"
node gettext.js -s "../public/portal/master_settings/lang/tr.po"
node gettext.js -s "../public/portal/master_settings/lang/el.po"

node gettext.js -s "../public/portal/lang/ru.po ../system/updater/lang/ru.po ../system/access.control/lang/ru.po"
node gettext.js -s "../public/portal/lang/de.po ../system/updater/lang/de.po ../system/access.control/lang/de.po"
node gettext.js -s "../public/portal/lang/bg.po ../system/updater/lang/bg.po ../system/access.control/lang/bg.po"
node gettext.js -s "../public/portal/lang/uk.po ../system/updater/lang/uk.po ../system/access.control/lang/uk.po"
node gettext.js -s "../public/portal/lang/es.po ../system/updater/lang/es.po ../system/access.control/lang/es.po"
node gettext.js -s "../public/portal/lang/tr.po ../system/updater/lang/tr.po ../system/access.control/lang/tr.po"
node gettext.js -s "../public/portal/lang/el.po ../system/updater/lang/el.po ../system/access.control/lang/el.po"

node gettext.js -s "../system/pages/loader/lang/ru.po ../system/access.control/lang/ru.po"
node gettext.js -s "../system/pages/loader/lang/de.po ../system/access.control/lang/de.po"
node gettext.js -s "../system/pages/loader/lang/bg.po ../system/access.control/lang/bg.po"
node gettext.js -s "../system/pages/loader/lang/uk.po ../system/access.control/lang/uk.po"
node gettext.js -s "../system/pages/loader/lang/es.po ../system/access.control/lang/es.po"
node gettext.js -s "../system/pages/loader/lang/tr.po ../system/access.control/lang/tr.po"
node gettext.js -s "../system/pages/loader/lang/el.po ../system/access.control/lang/el.po"

node gettext.js -s "../system/settings/lang/ru.po ../system/updater/lang/ru.po ../system/access.control/lang/ru.po"
node gettext.js -s "../system/settings/lang/de.po ../system/updater/lang/de.po ../system/access.control/lang/de.po"
node gettext.js -s "../system/settings/lang/bg.po ../system/updater/lang/bg.po ../system/access.control/lang/bg.po"
node gettext.js -s "../system/settings/lang/uk.po ../system/updater/lang/uk.po ../system/access.control/lang/uk.po"
node gettext.js -s "../system/settings/lang/es.po ../system/updater/lang/es.po ../system/access.control/lang/es.po"
node gettext.js -s "../system/settings/lang/tr.po ../system/updater/lang/tr.po ../system/access.control/lang/tr.po"
node gettext.js -s "../system/settings/lang/el.po ../system/updater/lang/el.po ../system/access.control/lang/el.po"

node gettext.js -s "../system/updater/lang/ru.po"
node gettext.js -s "../system/updater/lang/de.po"
node gettext.js -s "../system/updater/lang/bg.po"
node gettext.js -s "../system/updater/lang/uk.po"
node gettext.js -s "../system/updater/lang/es.po"
node gettext.js -s "../system/updater/lang/tr.po"
node gettext.js -s "../system/updater/lang/el.po"

pause